--------------------------------------------------------
--  File created - Tuesday-June-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURRENTEVENTSIGNUP
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" 
   (	"EVENTID" NUMBER, 
	"DISCORDID" RAW(8), 
	"SIGNUPORDER" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."EVENTS" 
   (	"EVENTID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CHANNELID" RAW(8), 
	"MESSAGEID" RAW(8), 
	"EVENTNAME" VARCHAR2(256 BYTE), 
	"EVENTDESCRIPTION" VARCHAR2(1024 BYTE), 
	"MAXPARTICIPANTS" NUMBER, 
	"ACCEPTEDEMOTEID" RAW(8), 
	"EVENTLENGTH" RAW(8), 
	"TIMEID" NUMBER, 
	"SCHEDULEID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTSCHEDULE
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."EVENTSCHEDULE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"REPEATDAYS" RAW(8), 
	"REPEATWEEKS" RAW(8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTTIMES
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."EVENTTIMES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TIMEZONE" VARCHAR2(20 BYTE), 
	"EVENTTIME" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXTRAPOINTSTABLE
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."EXTRAPOINTSTABLE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"USERID" RAW(8), 
	"POINTS" NUMBER, 
	"DESCRIPTION" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUILDMEMBERS
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."GUILDMEMBERS" 
   (	"DISCORDID" RAW(8), 
	"USERNAME" VARCHAR2(128 BYTE), 
	"NICKNAME" VARCHAR2(128 BYTE), 
	"TEAM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PASTEVENTSIGNUP
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."PASTEVENTSIGNUP" 
   (	"EVENTID" NUMBER, 
	"DISCORDID" RAW(8), 
	"EVENTDATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLAYERGEAR
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."PLAYERGEAR" 
   (	"DISCORDID" RAW(8), 
	"AP" NUMBER, 
	"AAP" NUMBER, 
	"DP" NUMBER, 
	"CLASS" NUMBER, 
	"PICTURELINK" VARCHAR2(1024 BYTE), 
	"EVASION" NUMBER, 
	"DR" NUMBER, 
	"ACC" NUMBER, 
	"PLEVEL" FLOAT(126), 
	"AXELEVEL" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SEASONSTARTPLAYERGEAR
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" 
   (	"DISCORDID" RAW(8), 
	"AP" NUMBER, 
	"AAP" NUMBER, 
	"DP" NUMBER, 
	"CLASS" NUMBER, 
	"PICTURELINK" VARCHAR2(1024 BYTE), 
	"EVASION" NUMBER, 
	"DR" NUMBER, 
	"ACC" NUMBER, 
	"PLEVEL" FLOAT(126), 
	"AXELEVEL" NUMBER, 
	"SEASONID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAMSLIST
--------------------------------------------------------

  CREATE TABLE "USER_S45318238"."TEAMSLIST" 
   (	"TEAMID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TEAMNAME" VARCHAR2(250 BYTE), 
	"TEAMLEADER" RAW(8)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURRENTEVENTSIGNUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."CURRENTEVENTSIGNUP_PK" ON "USER_S45318238"."CURRENTEVENTSIGNUP" ("EVENTID", "DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."EVENTS_PK" ON "USER_S45318238"."EVENTS" ("EVENTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENTTIMES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."EVENTTIMES_PK" ON "USER_S45318238"."EVENTTIMES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXTRAPOINTSTABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."EXTRAPOINTSTABLE_PK" ON "USER_S45318238"."EXTRAPOINTSTABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GUILDMEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."GUILDMEMBERS_PK" ON "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PASTEVENTSIGNUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."PASTEVENTSIGNUP_PK" ON "USER_S45318238"."PASTEVENTSIGNUP" ("EVENTID", "DISCORDID", "EVENTDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEASONSTARTPLAYERGEAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."SEASONSTARTPLAYERGEAR_PK" ON "USER_S45318238"."SEASONSTARTPLAYERGEAR" ("DISCORDID", "SEASONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."TABLE1_PK" ON "USER_S45318238"."EVENTSCHEDULE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."TABLE1_PK1" ON "USER_S45318238"."PLAYERGEAR" ("DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAMSTABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_S45318238"."TEAMSTABLE_PK" ON "USER_S45318238"."TEAMSLIST" ("TEAMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("CHANNELID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("MESSAGEID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("EVENTNAME" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("EVENTDESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("ACCEPTEDEMOTEID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("TIMEID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" MODIFY ("SCHEDULEID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTS" ADD CONSTRAINT "EVENTS_PK" PRIMARY KEY ("EVENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTTIMES
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."EVENTTIMES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTTIMES" MODIFY ("TIMEZONE" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTTIMES" MODIFY ("EVENTTIME" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTTIMES" ADD CONSTRAINT "EVENTTIMES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTSCHEDULE
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."EVENTSCHEDULE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTSCHEDULE" MODIFY ("REPEATDAYS" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTSCHEDULE" MODIFY ("REPEATWEEKS" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EVENTSCHEDULE" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SEASONSTARTPLAYERGEAR
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" MODIFY ("AP" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" MODIFY ("AAP" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" MODIFY ("DP" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" MODIFY ("SEASONID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" ADD CONSTRAINT "SEASONSTARTPLAYERGEAR_PK" PRIMARY KEY ("DISCORDID", "SEASONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUILDMEMBERS
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."GUILDMEMBERS" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."GUILDMEMBERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."GUILDMEMBERS" ADD CONSTRAINT "GUILDMEMBERS_PK" PRIMARY KEY ("DISCORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASTEVENTSIGNUP
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."PASTEVENTSIGNUP" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PASTEVENTSIGNUP" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PASTEVENTSIGNUP" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PASTEVENTSIGNUP" ADD CONSTRAINT "PASTEVENTSIGNUP_PK" PRIMARY KEY ("EVENTID", "DISCORDID", "EVENTDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PLAYERGEAR
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."PLAYERGEAR" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PLAYERGEAR" MODIFY ("AP" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PLAYERGEAR" MODIFY ("AAP" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PLAYERGEAR" MODIFY ("DP" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PLAYERGEAR" MODIFY ("CLASS" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."PLAYERGEAR" ADD CONSTRAINT "PLAYERGEAR_PK" PRIMARY KEY ("DISCORDID")
  USING INDEX (CREATE UNIQUE INDEX "USER_S45318238"."TABLE1_PK1" ON "USER_S45318238"."PLAYERGEAR" ("DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURRENTEVENTSIGNUP
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" MODIFY ("EVENTID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" MODIFY ("SIGNUPORDER" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" ADD CONSTRAINT "CURRENTEVENTSIGNUP_PK" PRIMARY KEY ("EVENTID", "DISCORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEAMSLIST
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."TEAMSLIST" MODIFY ("TEAMID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."TEAMSLIST" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."TEAMSLIST" MODIFY ("TEAMLEADER" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."TEAMSLIST" ADD CONSTRAINT "TEAMSTABLE_PK" PRIMARY KEY ("TEAMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXTRAPOINTSTABLE
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."EXTRAPOINTSTABLE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EXTRAPOINTSTABLE" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EXTRAPOINTSTABLE" MODIFY ("POINTS" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EXTRAPOINTSTABLE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "USER_S45318238"."EXTRAPOINTSTABLE" ADD CONSTRAINT "EXTRAPOINTSTABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURRENTEVENTSIGNUP
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" ADD CONSTRAINT "EVENTCONSTRAINT" FOREIGN KEY ("EVENTID")
	  REFERENCES "USER_S45318238"."EVENTS" ("EVENTID") ENABLE;
  ALTER TABLE "USER_S45318238"."CURRENTEVENTSIGNUP" ADD CONSTRAINT "USERCONSTRAINT" FOREIGN KEY ("DISCORDID")
	  REFERENCES "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."EVENTS" ADD CONSTRAINT "TIMECONSTRAINT" FOREIGN KEY ("TIMEID")
	  REFERENCES "USER_S45318238"."EVENTTIMES" ("ID") ENABLE;
  ALTER TABLE "USER_S45318238"."EVENTS" ADD CONSTRAINT "SCHEDULECONSTRAINT" FOREIGN KEY ("SCHEDULEID")
	  REFERENCES "USER_S45318238"."EVENTSCHEDULE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXTRAPOINTSTABLE
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."EXTRAPOINTSTABLE" ADD CONSTRAINT "POINTUSERCONSTRAINT" FOREIGN KEY ("USERID")
	  REFERENCES "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GUILDMEMBERS
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."GUILDMEMBERS" ADD CONSTRAINT "GUILDMEMBERTEAMCONSTRAINT" FOREIGN KEY ("TEAM")
	  REFERENCES "USER_S45318238"."TEAMSLIST" ("TEAMID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PASTEVENTSIGNUP
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."PASTEVENTSIGNUP" ADD CONSTRAINT "EVENTCONSTRAINTPREV" FOREIGN KEY ("EVENTID")
	  REFERENCES "USER_S45318238"."EVENTS" ("EVENTID") ENABLE;
  ALTER TABLE "USER_S45318238"."PASTEVENTSIGNUP" ADD CONSTRAINT "USERCONSTRAINTPREV" FOREIGN KEY ("DISCORDID")
	  REFERENCES "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLAYERGEAR
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."PLAYERGEAR" ADD CONSTRAINT "GEARUSERCONSTRAINT" FOREIGN KEY ("DISCORDID")
	  REFERENCES "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SEASONSTARTPLAYERGEAR
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" ADD CONSTRAINT "SEASONGEARCONSTRAINTID" FOREIGN KEY ("DISCORDID")
	  REFERENCES "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") ENABLE;
  ALTER TABLE "USER_S45318238"."SEASONSTARTPLAYERGEAR" ADD CONSTRAINT "SEASONGEAR" FOREIGN KEY ("DISCORDID")
	  REFERENCES "USER_S45318238"."PLAYERGEAR" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAMSLIST
--------------------------------------------------------

  ALTER TABLE "USER_S45318238"."TEAMSLIST" ADD CONSTRAINT "TEAMLEADCONSTRAINT" FOREIGN KEY ("TEAMLEADER")
	  REFERENCES "USER_S45318238"."GUILDMEMBERS" ("DISCORDID") ENABLE;
