--------------------------------------------------------
--  File created - Friday-June-18-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINROLES
--------------------------------------------------------

  CREATE TABLE "ADMINROLES" 
   (	"ROLEID" NUMBER, 
	"ROLENAME" VARCHAR2(256 BYTE), 
	"ROLEORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CURRENTSIGNUP
--------------------------------------------------------

  CREATE TABLE "CURRENTSIGNUP" 
   (	"DISCORDID" NUMBER, 
	"EVENTDATE" TIMESTAMP (6), 
	"SIGNUPORDER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EVENTDATA
--------------------------------------------------------

  CREATE TABLE "EVENTDATA" 
   (	"EVENTDATE" TIMESTAMP (6), 
	"EVENTNAME" VARCHAR2(256 BYTE), 
	"MESSAGEID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUILDMEMBERS
--------------------------------------------------------

  CREATE TABLE "GUILDMEMBERS" 
   (	"DISCORDID" NUMBER, 
	"USERNAME" VARCHAR2(64 BYTE), 
	"NICKNAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUILDTEAMS
--------------------------------------------------------

  CREATE TABLE "GUILDTEAMS" 
   (	"TEAMID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TEAMNAME" VARCHAR2(256 BYTE), 
	"TEAMLEADER" NUMBER, 
	"TEAMROLE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREVIOUSEVENTDATA
--------------------------------------------------------

  CREATE TABLE "PREVIOUSEVENTDATA" 
   (	"EVENTDATE" TIMESTAMP (6), 
	"EVENTNAME" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PREVIOUSSIGNUPDATA
--------------------------------------------------------

  CREATE TABLE "PREVIOUSSIGNUPDATA" 
   (	"DISCORDID" NUMBER, 
	"EVENTDATE" TIMESTAMP (6), 
	"CHANNELNAME" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEAMMEMBERS
--------------------------------------------------------

  CREATE TABLE "TEAMMEMBERS" 
   (	"TEAMID" NUMBER, 
	"DISCORDID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMINROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMINROLES_PK" ON "ADMINROLES" ("ROLEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CURRENTSIGNUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CURRENTSIGNUP_PK" ON "CURRENTSIGNUP" ("DISCORDID", "EVENTDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EVENTDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENTDATA_PK" ON "EVENTDATA" ("EVENTDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GUILDMEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUILDMEMBERS_PK" ON "GUILDMEMBERS" ("DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GUILDTEAMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUILDTEAMS_PK" ON "GUILDTEAMS" ("TEAMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREVIOUSEVENTDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVIOUSEVENTDATA_PK" ON "PREVIOUSEVENTDATA" ("EVENTDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PREVIOUSSIGNUPDATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREVIOUSSIGNUPDATA_PK" ON "PREVIOUSSIGNUPDATA" ("DISCORDID", "EVENTDATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEAMMEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMMEMBERS_PK" ON "TEAMMEMBERS" ("TEAMID", "DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PREVIOUSSIGNUPDATA
--------------------------------------------------------

  ALTER TABLE "PREVIOUSSIGNUPDATA" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "PREVIOUSSIGNUPDATA" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "PREVIOUSSIGNUPDATA" MODIFY ("CHANNELNAME" NOT NULL ENABLE);
  ALTER TABLE "PREVIOUSSIGNUPDATA" ADD CONSTRAINT "PREVIOUSSIGNUPDATA_PK" PRIMARY KEY ("DISCORDID", "EVENTDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEAMMEMBERS
--------------------------------------------------------

  ALTER TABLE "TEAMMEMBERS" MODIFY ("TEAMID" NOT NULL ENABLE);
  ALTER TABLE "TEAMMEMBERS" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "TEAMMEMBERS_PK" PRIMARY KEY ("TEAMID", "DISCORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMINROLES
--------------------------------------------------------

  ALTER TABLE "ADMINROLES" MODIFY ("ROLEID" NOT NULL ENABLE);
  ALTER TABLE "ADMINROLES" MODIFY ("ROLENAME" NOT NULL ENABLE);
  ALTER TABLE "ADMINROLES" MODIFY ("ROLEORDER" NOT NULL ENABLE);
  ALTER TABLE "ADMINROLES" ADD CONSTRAINT "ADMINROLES_PK" PRIMARY KEY ("ROLEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EVENTDATA
--------------------------------------------------------

  ALTER TABLE "EVENTDATA" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "EVENTDATA" MODIFY ("EVENTNAME" NOT NULL ENABLE);
  ALTER TABLE "EVENTDATA" ADD CONSTRAINT "EVENTDATA_PK" PRIMARY KEY ("EVENTDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EVENTDATA" MODIFY ("MESSAGEID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GUILDTEAMS
--------------------------------------------------------

  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMID" NOT NULL ENABLE);
  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMLEADER" NOT NULL ENABLE);
  ALTER TABLE "GUILDTEAMS" ADD CONSTRAINT "GUILDTEAMS_PK" PRIMARY KEY ("TEAMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMROLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREVIOUSEVENTDATA
--------------------------------------------------------

  ALTER TABLE "PREVIOUSEVENTDATA" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "PREVIOUSEVENTDATA" ADD CONSTRAINT "PREVIOUSEVENTDATA_PK" PRIMARY KEY ("EVENTDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CURRENTSIGNUP
--------------------------------------------------------

  ALTER TABLE "CURRENTSIGNUP" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "CURRENTSIGNUP" MODIFY ("EVENTDATE" NOT NULL ENABLE);
  ALTER TABLE "CURRENTSIGNUP" ADD CONSTRAINT "CURRENTSIGNUP_PK" PRIMARY KEY ("DISCORDID", "EVENTDATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CURRENTSIGNUP" MODIFY ("SIGNUPORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GUILDMEMBERS
--------------------------------------------------------

  ALTER TABLE "GUILDMEMBERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "GUILDMEMBERS" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "GUILDMEMBERS" ADD CONSTRAINT "GUILDMEMBERS_PK" PRIMARY KEY ("DISCORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURRENTSIGNUP
--------------------------------------------------------

  ALTER TABLE "CURRENTSIGNUP" ADD CONSTRAINT "CURRENTSIGNUPUSERCONSTRAINT" FOREIGN KEY ("DISCORDID")
	  REFERENCES "GUILDMEMBERS" ("DISCORDID") ENABLE;
  ALTER TABLE "CURRENTSIGNUP" ADD CONSTRAINT "CURRENTSIGNUPEVENTDATE" FOREIGN KEY ("EVENTDATE")
	  REFERENCES "EVENTDATA" ("EVENTDATE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GUILDTEAMS
--------------------------------------------------------

  ALTER TABLE "GUILDTEAMS" ADD CONSTRAINT "TEAMLEADUSERID" FOREIGN KEY ("TEAMLEADER")
	  REFERENCES "GUILDMEMBERS" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREVIOUSSIGNUPDATA
--------------------------------------------------------

  ALTER TABLE "PREVIOUSSIGNUPDATA" ADD CONSTRAINT "PREVSIGNUPUSERCONSTRAINT" FOREIGN KEY ("DISCORDID")
	  REFERENCES "GUILDMEMBERS" ("DISCORDID") ENABLE;
  ALTER TABLE "PREVIOUSSIGNUPDATA" ADD CONSTRAINT "PREVSIGNUPEVENTDATECONSTRAINT" FOREIGN KEY ("EVENTDATE")
	  REFERENCES "PREVIOUSEVENTDATA" ("EVENTDATE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAMMEMBERS
--------------------------------------------------------

  ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "TEAMMEMBERSTEAMID" FOREIGN KEY ("TEAMID")
	  REFERENCES "GUILDTEAMS" ("TEAMID") ENABLE;
  ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "TEAMMEMBERSUSERID" FOREIGN KEY ("DISCORDID")
	  REFERENCES "GUILDMEMBERS" ("DISCORDID") ENABLE;
