--------------------------------------------------------
--  File created - Wednesday-June-09-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GUILDMEMBERS
--------------------------------------------------------

  CREATE TABLE "GUILDMEMBERS" 
   (	"DISCORDID" NUMBER, 
	"USERNAME" VARCHAR2(64 BYTE), 
	"NICKNAME" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Table GUILDTEAMS
--------------------------------------------------------

  CREATE TABLE "GUILDTEAMS" 
   (	"TEAMID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TEAMNAME" VARCHAR2(256 BYTE), 
	"TEAMLEADER" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING;
--------------------------------------------------------
--  DDL for Table TEAMMEMBERS
--------------------------------------------------------

  CREATE TABLE "TEAMMEMBERS" 
   (	"TEAMID" NUMBER, 
	"DISCORDID" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING;
--------------------------------------------------------
--  DDL for Index GUILDMEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUILDMEMBERS_PK" ON "GUILDMEMBERS" ("DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
--------------------------------------------------------
--  DDL for Index GUILDTEAMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GUILDTEAMS_PK" ON "GUILDTEAMS" ("TEAMID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 ;
--------------------------------------------------------
--  DDL for Index TEAMMEMBERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAMMEMBERS_PK" ON "TEAMMEMBERS" ("TEAMID", "DISCORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 ;
--------------------------------------------------------
--  Constraints for Table TEAMMEMBERS
--------------------------------------------------------

  ALTER TABLE "TEAMMEMBERS" MODIFY ("TEAMID" NOT NULL ENABLE);
  ALTER TABLE "TEAMMEMBERS" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "TEAMMEMBERS_PK" PRIMARY KEY ("TEAMID", "DISCORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUILDTEAMS
--------------------------------------------------------

  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMID" NOT NULL ENABLE);
  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMNAME" NOT NULL ENABLE);
  ALTER TABLE "GUILDTEAMS" MODIFY ("TEAMLEADER" NOT NULL ENABLE);
  ALTER TABLE "GUILDTEAMS" ADD CONSTRAINT "GUILDTEAMS_PK" PRIMARY KEY ("TEAMID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUILDMEMBERS
--------------------------------------------------------

  ALTER TABLE "GUILDMEMBERS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "GUILDMEMBERS" MODIFY ("DISCORDID" NOT NULL ENABLE);
  ALTER TABLE "GUILDMEMBERS" ADD CONSTRAINT "GUILDMEMBERS_PK" PRIMARY KEY ("DISCORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GUILDTEAMS
--------------------------------------------------------

  ALTER TABLE "GUILDTEAMS" ADD CONSTRAINT "TEAMLEADUSERID" FOREIGN KEY ("TEAMLEADER")
	  REFERENCES "GUILDMEMBERS" ("DISCORDID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEAMMEMBERS
--------------------------------------------------------

  ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "TEAMMEMBERSTEAMID" FOREIGN KEY ("TEAMID")
	  REFERENCES "GUILDTEAMS" ("TEAMID") ENABLE;
  ALTER TABLE "TEAMMEMBERS" ADD CONSTRAINT "TEAMMEMBERSUSERID" FOREIGN KEY ("DISCORDID")
	  REFERENCES "GUILDMEMBERS" ("DISCORDID") ENABLE;
